from __future__ import annotations

import os

from bot.core_utils import BASE_DIR

LIVE_TRADES_STATE_PATH = os.path.join(BASE_DIR, "live_trades_state.json")
DEFAULT_ORDER_MONITOR_POLL_SECONDS = 10
DEFAULT_ORDER_MONITOR_RETRY_SECONDS = 30
DEFAULT_ENTRY_ORDER_WAIT_SECONDS = 8
DEFAULT_EXIT_LIMIT_MAX_RETRIES = 3
DEFAULT_EXIT_LIMIT_RETRY_SECONDS = 1.0
DEFAULT_EXIT_ORDER_VERIFY_SECONDS = 4
EXIT_LIMIT_FAILURE_TAG = "[EXIT_LIMIT_RETRY_FAILED]"
DEFAULT_ENTRY_TOKEN_RESOLVE_WAIT_SECONDS = 30
DEFAULT_ENTRY_TOKEN_RESOLVE_POLL_SECONDS = 2.0
DEFAULT_MAX_MARKET_ENTRY_PRICE = 0.56
DEFAULT_EXIT_SIZE_DECIMALS = 4
